sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zyy200501
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tD56coFfEESQd4Dh82f
    access-key-secret: FoJOyKiyN2erlPPeooZVORV9CDeHzW
    bucket-name: zhaoyang-take-out
